### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jessebridge** [bane73/firebase4j#10]
Could you please add a section in your readme that covers how to import the package. Cheers

**Comment by bane73** [comment]
I haven't maintained this project since I first wrote it in 2012. I'm flattered at how many people have played with it over the years though!

Anyways, I never did package for Maven, etc -- but apparently years ago I found a neat little service that will dynamically do it for you (I really don't recall doing this, but it's linked to my profile lol) and added a page on using that service to package it up for use in a Maven project. 

Give it a whirl here, hopefully it still works: https://jitpack.io/p/bane73/firebase4j
😄

**Comment by bane73** [comment]
I am assuming my suggestion worked for you, @jessebridge so I am closing this issue.
