### ISSUE TITLE
Best practices for Security about Realtime Database with Firebase4j?

### ISSUE THREAD

**Issue by ericciaparicio** [bane73/firebase4j#13]
I developed a solution about Push Notifications with Firebase. I am using Realtime Database, FCM, Cloud Functions and Firebase4J. The solution is working OK but I have doubt about security. The rules on the Realtime Database are:

`{
   "rules": {
    ".read": true,
    ".write": true
  }
}`

I read that this config is not appropiate for production. But I dont know how should configure the security in Firebase4J.

Regards
ER

**Comment by bane73** [comment]
@ericciaparicio : I'm sorry, but I can't provide this level of support on this project. This project started out as a proof-of-concept and has never really gotten out of alpha. I myself don't use it and I really don't follow Firebase too much these days, as I'm off doing different types of projects. I'm very happy this project is used by so many people but I consider this project more a helping-hand for them to arrive at their own solutions rather than a drop-in framework that provides an entire solution.

My suggestion would be to consider one of three possible approaches:

1. investigate the issue yourself and then branch this project, apply any extra code you feel is needed, and then send me a pull-request; I'd be more than happy to include extra functionality in this project if you find it solves a need for you

1. look into the many projects which have already forked mine and see if they happen to offer new functionality that might address your need

1. look into the official Firebase java API (which did not exist when I wrote this project, but which was quickly developed soon after I created this project) and see if they might address your concern and if you might be able to use their API instead

If you learn enough through other projects but still see a need to include that functionality into this project, then please do send me a pull-request and I will likely accept it.

Best,
Brandon
