### ISSUE TITLE
Maven dependency of project

### ISSUE THREAD

**Issue by hriships-zz** [bane73/firebase4j#3]
This library looks promising.
It would be great, if we can get it in the form of maven/gradle dependcies.

**Comment by bane73** [comment]
OK I converted it to Maven.  Just be aware, I basically abandoned this as a prototype back when Firebase was still a beta service; since then, of course, Firebase has grown a ton but I never found the time to keep up.  If you end up liking this project I would be very interested to see what you come up with!

**Comment by hriships-zz** [comment]
Hey that was so quick. Thanks a ton.
At present i'm bit occupied but definately I will get back soon to point that you have mentioned.
